# Generated by Django 2.2.1 on 2019-05-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_id_cate_95fea8_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
