# Generated by Django 2.2.1 on 2019-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190514_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(through='core.ProductCategory', to='core.Product'),
        ),
    ]
