# Generated by Django 2.2.1 on 2019-05-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190514_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(db_column='id_department', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='core.Department'),
        ),
    ]
