# Generated by Django 2.2.1 on 2019-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190514_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(db_column='cs_gender', max_length=1, null=True),
        ),
    ]
